#!/usr/bin/env bash
# This script retrieves lines containing the word "bash" from the 'ps' command output.
# We disable SC2009 for the 'grep' command since it's intentional here.

ps -aux | grep bash
