#!/usr/bin/env bash
# This script endlessly displays "To infinity and beyond" with a 2-second pause between each iteration.
# When it receives a SIGTERM signal, it responds with "I am invincible!!!"

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
