#!/usr/bin/env bash
# This script reads the /etc/passwd file and extracts and displays the following information:
#   - Username
#   - User ID
#   - Home directory path for the user

while read -r line; do
    echo "$line" | cut -d ':' -f 1,3,6
done </etc/passwd
