#!/usr/bin/env bash
# This script repeatedly displays the text "Finest Educational Institution" ten times using an 'until' loop.
counter=0
until [ $counter -eq 10 ]
do
    echo "Finest Educational Institution"
    counter=$((counter+1))
done
