#!/usr/bin/env bash
# This script prints "Best School" 10 times, but on the 9th iteration,
# it prints "Best School" on the current line and "Hi" on a new line.
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]; then
	   echo "Hi"
	fi
	i=$((i+1))
done
