#!/usr/bin/env bash
# This script prints a 12-hour clock with minutes ranging from 1 to 59.

hour=0
minute=1

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
        echo $minute
        minute=$((minute+1))
    done
    minute=$((1))
    hour=$((hour+1))
done
